name: Build and deploy Backend to Azure Web App - ApiJobbahub

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # Start de workflow alleen als er iets in de /backend map verandert
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Dit is nodig om in te loggen op Azure
      contents: read # Dit is nodig om je code te kunnen 'checken'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies and build
        # 👇 CORRECTIE 1: Voer deze commando's uit in de /backend map
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ApiJobbahub"
          slot-name: "Production"
          # 👇 CORRECTIE 2: Vertel Azure om alleen de /backend map te deployen
          package: ./backend
