name: Build and deploy Backend to Azure Web App - ApiJobbahub

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Vereist voor OIDC login
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies and build
        # Commando's uitvoeren in de /backend map
        working-directory: ./backend
        run: |
          npm install
          npm run build

      # HIER WORDT DE INLOGMETHODE GEWIJZIGD NAAR OIDC
      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          # Gebruik de Subscription ID uit GitHub Secrets
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # OIDC vertrouwensrelatie wordt automatisch gebruikt
          # client-id en tenant-id zijn NIET MEER nodig

      # Zorg ervoor dat de App Service Opstartopdracht is ingesteld op "npm start"
      # De 'package' wijst naar de /backend map om de inhoud te uploaden naar wwwroot
      - name: "Deploy Backend to Azure Web App"
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ApiJobbahub"
          slot-name: "Production"
          # De output van de build (de /backend map) wordt gedeployed
          package: ./backend
